config/routes.rb
WikiRoots::Application.routes.draw do

  resources :wiki_pages, :except => [:destroy]
  resources :wiki_trees, :only => [:index, :show]

  root :to => 'wiki_trees#index'

end

app/models/wiki_page.rb
require 'wikipedia'

class WikiPage < ActiveRecord::Base
  has_ancestry

  belongs_to :tree, :class_name => "WikiTree"

  before_save :title_to_downcase

  scope :roots, where("is_root")

  def title_to_downcase
    title.downcase
  end


  # For tracing we must search for the end of the road or a loop
  def trace
    
    path = WikiPath.new
    
    page = self

    tree = nil

    wikipage = Wikipedia.find(title)

    page.update_attributes :fetched_at => Time.now

    # If page has a parent or is root we must stop (we can fetch the cached path or it's a loop)
    # If there's no page... we reached the end of the road
    while page.parent_id.blank? and !page.is_root
      
      path.pages << page

      first_link_title = wikipage.content
      first_link_title.gsub!("\n", "")
      # We must get rid of infoboxes, metadata and Image and FIle links before we get the link title
      first_link_title.gsub!(%r{(?<re>\{\{(?:(?> [^\{\}]+ )|\g<re>)*\}\})}x, "")

      # We get the whole [[ ... ]] fragments even when they have recursive [[...]] blocks 
      # and then must get the first which doesn't point to a File, Image...
      first_link_title = first_link_title.scan(%r{(?<re>\[\[(?:(?> [^\[\]]+ )|\g<re>)*\]\])}x).flatten.detect{|m| !m.match(/^\[\[[^\]\|].*:/)}
      first_link_title = first_link_title.split("|").first.gsub("]", "").gsub("[", "") unless first_link_title.nil?

      if first_link_title.nil?
        page.update_attributes :is_root => true
        page = nil
      else
        wikipage = Wikipedia.find(first_link_title)

        parent_page = WikiPage.find_by_title(first_link_title)
        parent_page ||= WikiPage.create :url => "", :title => first_link_title, :fetched_at => Time.now, :is_root => false

        page.parent = parent_page
        page.save

        page = parent_page        
      end
    end

    parent_pos = path.pages.index(page.parent) unless page.parent.nil?

    # If parent is not in the path then we have a cached path
    # and the current tree is parent's tree
    if !page.parent.nil? and parent_pos.nil?
   
      path.pages.concat(page.ancestors.reverse)
 
      # I don't understand why page.tree does not work :S
      tree =  WikiTree.find(page.parent.wiki_tree_id)

      path.pages.concat(tree.roots).uniq!
    elsif page.is_root
      
      # I don't understand why page.tree does not work :S
      tree =  WikiTree.find(page.wiki_tree_id.inspect)
      # If page is a root then we should add all the other roots to the path and 
      # the current tree is the root's tree
      path.pages.concat(tree.roots).uniq!

    else
      # If parent is in the path then we have a loop
      # we must get the roots 
      roots = path.pages.slice parent_pos-1, path.pages.length - (parent_pos - 1)

      # create a tree
      tree = WikiTree.create :name => roots.map(&:title).join(" - ")      
      # remove the parent page to every root and indicate it's a root
      roots.reverse.each do |root|
        root.is_root = true
        root.parent_id = nil
        root.save!
      end

    end


    # and now we assign every page to the tree
    path.pages.each do |page|
      page.wiki_tree_id = tree.id
      page.save!
    end


    path

  end

end

app/models/wiki_path.rb
class WikiPath
  attr_reader :pages

  def initialize
    @pages = []
  end

  def distance 
    @pages.length - 1
  end

end

app/models/wiki_tree.rb
class WikiTree < ActiveRecord::Base
  has_many :pages, :class_name => "WikiPage"
  has_many :roots, :class_name => "WikiPage", :conditions => "is_root"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/wiki_pages_controller.rb
class WikiPagesController < ApplicationController

  def create

     wikipedia_page = Wikipedia.find(params[:wiki_page][:title])

     wiki_page = WikiPage.find_or_create_by_title wikipedia_page.title

     if wiki_page.fetched_at.nil? or (wiki_page.fetched_at  < 7.days.ago.to_date)
       wiki_page.trace
     end

     redirect_to wiki_trees_path
  end
end

app/controllers/wiki_trees_controller.rb
class WikiTreesController < ApplicationController

  def index
    @wiki_trees = WikiTree.all
  end

  def show
    @wiki_tree = WikiTree.find params[:id]
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper

  def url_to_wikipedia path
    "#{Settings["wikipedia_domain"]}#{path}"
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WikiRoots</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body class="<%=params[:controller].underscore%>">

<%= render :partial=>"shared/header" %>

<%= yield %>

</body>
</html>

app/views/shared/_header.html.erb
<h1>Wiki Roots </h1>
<%= render :partial => "wiki_pages/embedded_form", :locals => {:page => WikiPage.new} %>

app/views/wiki_pages/_embedded_form.html.erb
<%= form_for page do |f| %>
<%= f.label :title, t(".search_page") %>
<%= f.text_field :title %>
<%= f.submit t(".search_button") %>
<% end %>

app/views/wiki_trees/_page.html.erb
<li><%= link_to(page.title, url_to_wikipedia(page.title)) %>
  <% unless page.children.blank? %>
  <ul>
    <%= render :partial => "page", :collection => page.children %>
  </ul>
  <% end %>
</li>

app/views/wiki_trees/index.html.erb
<% @wiki_trees.each do |tree|%>
<li><%= link_to tree.name, wiki_tree_path(tree.id) %></li>
<% end %>

app/views/wiki_trees/show.html.erb
<h2><%=@wiki_tree.name%></h2>

<h3>Páginas</h3>

<ul>
  <%= render :partial => "page", :collection => @wiki_tree.roots %>
</ul>